apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: helloworld-go-native
  namespace: default
spec:
  template:
    spec:
      containers:
        - image: harbor.nbfc.io/nubificus/helloworld-go:latest
          env:
            - name: TARGET
              value: "Go Sample v1"
