name: Docker build & push

on:
  push:
    branches: [ main ]
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ main ]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: harbor.nbfc.io/nubificus
  # github.repository as <account>/<repo>
  IMAGE_NAME: helloworld-go 
  #${{ github.repository }}


jobs:
  build:
    runs-on: [self-hosted, "${{ matrix.arch }}", "go" ]
    permissions:
      contents: read
      packages: write
    env:
      ARCH: ${{ matrix.arch }}

    strategy:
      matrix:
        arch: [x86_64, aarch64]
      fail-fast: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.HARBOR_USER }}
          password: ${{ secrets.HARBOR_SECRET }}

      # Extract metadata (tags, labels) for Docker
      # https://github.com/docker/metadata-action
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      # Build and push Docker image with Buildx (don't push on PR)
      # https://github.com/docker/build-push-action
      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          file: Dockerfile
          no-cache: true
          push: ${{ github.event_name != 'pull_request' }}
          #push: true #${{ github.event_name != 'pull_request' }}
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.ARCH }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
                ARCHTAG=${{ env.ARCH }}

  create_manifest:
    runs-on: [self-hosted]
    #if: github.event_name != 'pull_request'
    needs: build

    steps:
      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      - name: Log into registry ${{ env.REGISTRY }}
        #if: github.event_name != 'pull_request'
        uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.HARBOR_USER }}
          password: ${{ secrets.HARBOR_SECRET }}

      - name: Create manifest
        run: |
          docker manifest rm ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }} || true
          docker manifest create ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest \
            --amend ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:x86_64 \
            --amend ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:aarch64
          docker manifest push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
